### PR TITLE
Improve build-examples.sh

### PR DESCRIPTION
**Pull request by szepeviktor**
Now it's simpler.

### CODE REVIEW

**Comment by szepeviktor** [comment]
A more technical way
```bash
find comfy/examples/ -type f -name "*.rs" -print0 | xargs -0 -n1 -- basename -z -s .rs | xargs -0 -n1 -- echo cargo build --features blobs --example
```

**Comment by darthdeus** [comment]
Thanks, tho I'm not sure if the xargs version is really much better, it feels overly complicated for something that's very simple at its core.

**Comment by szepeviktor** [comment]
`for` cannot safely process file lists.

**Comment by darthdeus** [comment]
I mean I get that _in theory_, but this iterates over a list of examples which are known ahead of time. There's zero safety risks here. I'd rather have the script be readable.

**Pull request merged**
